# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -s .settings.xml -B package --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        path: ${{ github.workspace }}/target/*.jar
    
    - name: Generate changelog
      id: Changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.2
      with:
        # Target GitHub repo in the form of organization/repository.
        repo: anthunt/aws-exporter
        # Username of the owner of target GitHub repo.
        user: anthunt
        # Name of project on GitHub.
        project: aws-exporter
        # To make more than 50 requests per hour your GitHub token is required.
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Tag Name
        id: tag
        uses: ashley-taylor/regex-property-action@v1.2
        with:
          value: ${{ github.ref }}
          regex: ".*/"
          flags: "" # Optional, defaults to "g"
          replacement: ""

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ steps.tag.outputs.value }}
        tag_name: ${{ steps.tag.outputs.value }}
        body: |
          ${{ steps.Changelog.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Make zip
      run: zip --junk-paths aws-exporter-${{ steps.tag.outputs.value }} target/*.jar
      
    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./aws-exporter-${{ steps.tag.outputs.value }}.zip
        asset_name: aws-exporter-${{ steps.tag.outputs.value }}.zip
        asset_content_type: application/zip
    
